# Docker-compose stack for development purposes
# DO NOT USE THIS IN PRODUCTION

name: clic-template

include:
  - path: directus-config/directus.yaml
services:
  app:
    build:
      dockerfile: Dockerfile.dev
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /app

  caddy:
    image: caddy
    volumes:
      - "./Caddyfile.dev:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
